### ISSUE TITLE
Git clone fails in submodule

### ISSUE THREAD

**Issue by nomadeon** [RIPE-NCC/ripe-atlas-software-probe#103]
On Debian, the following fails:
 git clone --recursive https://github.com/RIPE-NCC/ripe-atlas-software-probe.git
 
With error:
fatal: remote error: upload-pack: not our ref d72872cc6bb9ed5da47dcf1dc726fd8a36c6058f
fatal: Fetched in submodule path 'probe-busybox', but it did not contain d72872cc6bb9ed5da47dcf1dc726fd8a36c6058f. Direct fetching of that commit failed.

Have tried the following alternatives that result in the same error
Alt 1:
git clone https://github.com/RIPE-NCC/ripe-atlas-software-probe.git # not recursive
cd ripe-atlas-software-probe
git submodule update --init --recursive
Alt 2:
git submodule init
git submodule update --no-fetch

The AI overlords inform me this error could indicate:
1. The submodule repository might have been force-pushed, and the commit no longer exists.
2. The submodule might be pointing to a commit that hasn't been pushed to the remote repository.

**Comment by Oorweeg** [comment]
+1 On this issue, ended up doing a checkout of an earlier commit pre 56fbfbf50fed7bb06268c5721076e6a62e552039 and manually cloning the submodule to be able to get it to build.

**Comment by mtheofy** [comment]
+1 on this. 

@Oorweeg  can you please share some more details of your solution?

**Comment by Oorweeg** [comment]
Looks like the issue with the submodule repo has been fixed so haven’t tried 5090 again yet, but I built against 5080 for debian using the following method

```
git clone --recursive https://github.com/RIPE-NCC/ripe-atlas-software-probe.git

cd ripe-atlas-software-probe

rm -rf probe-busybox

git clone https://github.com/RIPE-NCC/ripe-atlas-probe-measurements.git probe-busybox

git checkout 67b0736887d33d1c42557e7c7694cbd4e5d8e6ee

git submodule update

build-config/debian/bin/make-config
```

**Comment by Oorweeg** [comment]
Confirmed 5090 builds OK for me now anyway now the submodule repo is fixed 👍

**Comment by nomadeon** [comment]
Confirmed working here as well, will close.
Thanks all!
