### ISSUE TITLE
Requirements List

### ISSUE THREAD

**Issue by Knight1** [RIPE-NCC/ripe-atlas-software-probe#19]
I think we should make a List of needed commands for the Software to function properly. 

We have to make sure that there are no missing commands inside each OS. There are already differences between RedHat 7 and 8. Now we have Debian support as well but afaik with no minimum OS and no Dependencies. 

Any ideas how to solve that problem?

For Example: fakeroot ist needed under Debian @ rpi

**Comment by michel-stam** [comment]
Hi @Knight1 

Is this still a problem for you? I see this issue has not been looked at for a very long time.

Regards,

Michel
