### ISSUE TITLE
Needed dependency for deb

### ISSUE THREAD

**Issue by Ideafix0** [RIPE-NCC/ripe-atlas-software-probe#21]
Adding openssl-devel to:
 ```apt update && apt install git tar fakeroot libssl-dev autoconf automake libtool build-essential```
so it looks something like:
 ```apt update && apt install git tar fakeroot openssl-devel libssl-dev autoconf automake libtool build-essential```
in file:
INSTALL.rst
to be able to install in Ubuntu

**Comment by xtaran** [comment]
There is no `openssl-devel` package on neither Debian nor Ubuntu. `-devel` sounds more like a package name suffix typical for the RPM world. The Debian equivalent of it is `libssl-dev` which is already in there.

**Comment by PhilipHomburg** [comment]
I'll close this issue. It is not clear to me which version of Ubuntu would need openssl-devel in addition to libssl-dev.
