### ISSUE TITLE
issues related to cross compiling for yocto

### ISSUE THREAD

**Issue by Ideafix0** [RIPE-NCC/ripe-atlas-software-probe#22]
We need to be able to pass the --host parameter into "configure" through "make-deb", so we can make a yocto recipe.

 A simple fix would be to change, in file make-deb:

./configure

to

./configure $@

**Comment by PhilipHomburg** [comment]
Feel free to add an option to the script to do what you want.

**Comment by PhilipHomburg** [comment]
Note that if it is probe-busybox that doesn't compile, then we first need to fix it in that repo (https://github.com/RIPE-NCC/ripe-atlas-probe-busybox)
