### ISSUE TITLE
Feature Request: for every tagged release, provide pre-compiled binaries of atlasswprobe

### ISSUE THREAD

**Issue by netravnen** [RIPE-NCC/ripe-atlas-software-probe#27]
## Feature Request

Provide downloadable installer files when a new release is tagged

_I.e. when a release is tagged for a git commit, upload pre-compiled `.deb` and/or `.rpm` files available on [RIPE-NCC/ripe-atlas-software-probe/releases](/RIPE-NCC/ripe-atlas-software-probe/releases)_ _(e.g. release [5010](/RIPE-NCC/ripe-atlas-software-probe/releases/tag/v5010))_

**Comment by netravnen** [comment]
[atlasswprobe-5010-1-amd64.deb.zip](https://github.com/RIPE-NCC/ripe-atlas-software-probe/files/4210267/atlasswprobe-5010-1-amd64.deb.zip)

**Comment by Knight1** [comment]
You mean like this? https://github.com/Knight1/ripe-atlas_packages-test/releases

I don't think so. They made clear that they only provide the Software and CentOS Tools.

**Comment by netravnen** [comment]
> You mean like this? https://github.com/Knight1/ripe-atlas_packages-test/releases

Yep.

**Comment by netravnen** [comment]
[INSTALL.rst](https://github.com/RIPE-NCC/ripe-atlas-software-probe/blob/83ef3de9ce007be9a1533a36e84af9c7b8bbcc48/INSTALL.rst)

> Currently only the Debian Build system includes support for amd64, arm64, and armhf.

Is there a public discussion about why this is a problem atm. ?

Somewhere publicly would be prefered.

**Comment by Zeik0s** [comment]
@netravnen i've created an automated workflow for building the sw probe with github actions. 

Currently the files are only stored as artifacts, i still need to figure out how i can add them as release in my fork. 
But i would be happy if someone would try the built packages. I built them for Debian x64, aarch64 and armv7 (armhf). 

Currently i also don't have a mechanism, that creates a release when a new tag was created here in this repo.

The Workflows called build do have the packages as zipped artifacts attached. 
https://github.com/Zeik0s/ripe-atlas-software-probe/actions/workflows/build.yml
