### ISSUE TITLE
Unsupported architecture armv6l

### ISSUE THREAD

**Issue by Tuffiglig** [RIPE-NCC/ripe-atlas-software-probe#29]
Hey.
First thanks for the great job!

It would be nice, if it is possible to check the architecture in
"ripe-atlas-software-probe/build-config/debian/bin/make-deb" at the beginning of the file.
Tried it first on an old Raspberry Pi 1 Mod. B (ARMv6)
and it ended with "Unsupported architecture armv6l" after a long time of compiling (for nothing).

Thanks,
Tuffi

**Comment by Tuffiglig** [comment]
I added to the file `make-deb`:
After
`armv7l)
        ARCH=armhf
;;`
i added this
`armv6l)
        ARCH=armhf
;;`
on my "Raspberry Pi 1 Mod. B - ARMv6 (32 Bit) / 512 MB RAM",
and it compiled successful the file atlasswprobe-5010-2.deb
after installing it, everything seems to work good.
https://atlas.ripe.net/probes/1000251/

Sorry. Don't know how to make a new line in the code brackets to make it look like in the original file.

**Comment by PhilipHomburg** [comment]
I just released v5010.3 where I added armv6l and added a check for the architecture at the beginning.
