### ISSUE TITLE
Limit SSH keylength to 2048 bit

### ISSUE THREAD

**Issue by stv0g** [RIPE-NCC/ripe-atlas-software-probe#30]
When installing the probe on Fedora 31, it defaults to a 4096 bit RSA SSH key.
This keylength however, is rejected by the application website.

Shall we change the invocation of `ssh-keygen` to `ssh-keygen -b 2048` ?

**Comment by stv0g** [comment]
Same happens with CentOS 8..

**Comment by stv0g** [comment]
Sorry, seems to be duplicate of #28. However, I still encounter the issue on a fresh install..

**Comment by stv0g** [comment]
@PhilipHomburg there now seem to be a release for CentOS 8 in 5020.

I am wondering how this can work without my PR. Is there nobody else experiencing the issue?

Has be maximum key length been increased on the server side?

**Comment by robert-kisteleki** [comment]
5020 was indeed released a few days ago and it's also available for CentOS 8.

Somewhat related, we updated the server side software to accept RSA 2k-4k keys as well as ECDSA and ED25519 keys. So strictly speaking limitig RSA keys to 2 kbits is no longer needed.

**Comment by stv0g** [comment]
Thanks for the update. In this case this issue and the related PR become obsolete.
