### ISSUE TITLE
Checklist to troubleshoot probe (registered) but not created

### ISSUE THREAD

**Issue by swapneelp** [RIPE-NCC/ripe-atlas-software-probe#33]
Hello! I had shared this on atlas-sw-probes mailing list, sharing this here as well. I've registered a software probe successfully on Ubuntu 16.04.4 LTS but it hasn't been created it yet. Usually, this is done in 10-15 minutes. 

The machine is behind a pfSense firewall which as far as I can tell isn't blocking any requests. Can you share a troubleshooting checklist which I can try to see where the problem is?

If I may make a suggestion to also update the troubleshooting page[1] for software probes  Thank you. 

[1]: https://atlas.ripe.net/docs/troubleshoot-probe-issues/

**Comment by Knight1** [comment]
In the state directory are some log and error files :)

**Comment by michel-stam** [comment]
Hi @swapneelp,

Given the age of the ticket, I hope your issue has been resolved and I will be closing the ticket. If I am wrong, please reopen it and I will help you.

Regards,

Michel
