### ISSUE TITLE
Wrong Local Address

### ISSUE THREAD

**Issue by Hypopheralcus** [RIPE-NCC/ripe-atlas-software-probe#34]
The Local Address uses the wrong interface. I have setup an Rapsberry Pi and play a little bit with wireguard after bringing up the Wireguard Interface the Probe #1000506 shows the IP form the wg0. Although the interface has no active link. Only a static IP. Currently there are 3 Interfaces.

1: lo:
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:91:07:b8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.2/24 brd 192.168.178.255 scope global noprefixroute wlan0
6: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 192.168.150.1/24 scope global wg0
       valid_lft forever preferred_lft forever

**Comment by PhilipHomburg** [comment]
Yes, that's something that can be done of the Atlas backend software. Currently it picks something like the first interface that is not lo. This can be improved by taking default routes into account

**Comment by alaunay** [comment]
I'm also having trouble with this... It runs on a server on which the first not lo interface has an rc1918 ip address, but a correct ipv6 address (eth0); and a fourth interface in a vlan that has the correct ipv4 address (eth0.832). Probe ID 1001346 . The Probe address discovery gives nothing for ipv4, only a connection address for ipv6, and no ip echo service or local IP. I tried running the last devel from mid-november (5020-4), on a Debian 10, without more success.

**Comment by PhilipHomburg** [comment]
> I'm also having trouble with this... It runs on a server on which the first not lo interface has an rc1918 ip address, but a correct ipv6 address (eth0); and a fourth interface in a vlan that has the correct ipv4 address (eth0.832). Probe ID 1001346 . The Probe address discovery gives nothing for ipv4, only a connection address for ipv6, and no ip echo service or local IP. I tried running the last devel from mid-november (5020-4), on a Debian 10, without more success.

It seems that your probe is not doing any work, it also doesn't report it's IP addresses. Maybe you can check if there is anything interesting in log files or in /var/atlas-probe/data

**Comment by alaunay** [comment]
There is stuff in  /var/atlas-probe/data:

ls
new  oneoff  out

# ls new/
main  ooq.0  ooq.1  ooq.2  ooq.3  ooq.4  ooq.5	ooq.6  ooq.8  reboot-count.old	simpleping  v6addr.txt	v6addr.vol

# ls out/
(lots of 7.276* files like this:
-rw-r--r-- 1 atlas nogroup 11799 déc.  14 13:46 7.26799166
-rw-r--r-- 1 atlas nogroup  1137 déc.  14 13:47 7.26799167

plus
-rw-r--r-- 1 atlas nogroup    57 déc.  12 23:48 main
-rw-r--r-- 1 atlas nogroup  2561 déc.  12 23:47 7.26796887
-rw-rw-r-- 1 atlas nogroup  2952 déc.  12 23:47 simpleping
-rw-r--r-- 1 atlas nogroup  1760 déc.  12 23:47 v6addr.txt
drwxrwxr-x 2 atlas nogroup    40 déc.  12 23:47 ooq10

the oneoff directory is empty though.

I can give you ssh access to the server if you want.

**Comment by PhilipHomburg** [comment]
Ssh would be useful. Maybe we should take it to email. My email address is <phomburg@ripe.net>

**Comment by PhilipHomburg** [comment]
Doesn't seem to be an issue with this repo

**Comment by alaunay** [comment]
The problem was that the tcp port 8080 was already used by something else. By changing the port for the other app, ripe atlas ran perfectly.

**Comment by PhilipHomburg** [comment]
Ah. I have some code to make this port configurable. I'll take a look what is needed to finish it.
