### ISSUE TITLE
RPM package requires sysvinit-tools

### ISSUE THREAD

**Issue by mkowalski** [RIPE-NCC/ripe-atlas-software-probe#35]
```
 Problem: cannot install the best update candidate for package atlasswprobe-5000-2.el7.x86_64
  - nothing provides sysvinit-tools needed by atlasswprobe-5020-1.el7.x86_64
```
The error above is being shown when trying to install the software probe from `https://ftp.ripe.net/ripe/atlas/software-probe/centos7` repo. Given that CentOS 7 is shipped with systemd, not with sysvinit, the requirement should be loosened.

Currently the workaround to install the package is to manually install it using `rpm` as below

```
# dnf repoquery --location atlasswprobe
https://ftp.ripe.net/ripe/atlas/software-probe/centos7/x86_64/atlasswprobe-5000-1.el7.x86_64.rpm
https://ftp.ripe.net/ripe/atlas/software-probe/centos7/x86_64/atlasswprobe-5000-2.el7.x86_64.rpm
https://ftp.ripe.net/ripe/atlas/software-probe/centos7/x86_64/atlasswprobe-5010-1.el7.x86_64.rpm
https://ftp.ripe.net/ripe/atlas/software-probe/centos7/x86_64/atlasswprobe-5020-1.el7.x86_64.rpm

# rpm -Uvh --nodeps https://ftp.ripe.net/ripe/atlas/software-probe/centos7/x86_64/atlasswprobe-5020-1.el7.x86_64.rpm
Retrieving https://ftp.ripe.net/ripe/atlas/software-probe/centos7/x86_64/atlasswprobe-5020-1.el7.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:atlasswprobe-5020-1.el7          ################################# [ 50%]
Cleaning up / removing...
   2:atlasswprobe-5000-2.el7          ################################# [100%]
```

**Comment by PhilipHomburg** [comment]
I don't think the current code works without systemd. I.e, there are only systemd unit files to start the atlas probe.

We cannot support every possible configuration. Certainly not non-default configurations of platforms that we do support.

However, if anyone has patches then I look into merging them.

**Comment by mkowalski** [comment]
I think you are mixing things in here, sysvinit *is not* systemd. A default configuration on CentOS 7 *does not* provide sysvinit.

To make it clear - the current package is not installing on a clean, default CentOS 7.

**Comment by Jamesits** [comment]
Plus the current code do work without systemd. I've been using it without a systemd for a long time.

**Comment by PhilipHomburg** [comment]
The rpm require sysvinit-tools. This is mostly unrelated to the sysvinit system. I have quite a few VMs that run centos7 with the atlasprobe package. Are you sure you are not running centos8?

Good to here that is works with sysvinit on centos. I wonder how that works though. Does syvinit on centos understand systemd unit files?

**Comment by Jamesits** [comment]
In fact you don't need any special init system to make it work. Just launch the atlas executable in any way you want and it will work fine.

**Comment by PhilipHomburg** [comment]
In my book if you need to mount tmpfs manually and start atlas manually then it is not a complete package. I can't list that as 'works'.
