### ISSUE TITLE
RSA host key for IP address '..' not in list of known hosts

### ISSUE THREAD

**Issue by chriselsen** [RIPE-NCC/ripe-atlas-software-probe#40]
My probe (ID: 1000597) is unable to connect to the controller. 
The error message in /var/atlas-probe/status/ssh_err.txt states "RSA host key for IP address '2a01:4f8:110:40b2::2' not in list of known hosts." 
That IPv6 address corresponds to the host ctr-fsn01.atlas.ripe.net.
There is an entry for that host in /var/atlas-probe/.ssh/known_hosts. 

How does the probe receive an updated known_hosts list?

**Comment by PhilipHomburg** [comment]
This probe is connected. The error message is a harmless diagnostic from ssh. I don't know how to suppress that.
