### ISSUE TITLE
couple dpkg install errors

### ISSUE THREAD

**Issue by ak370** [RIPE-NCC/ripe-atlas-software-probe#42]
Hi, I got around the below, but you might want to fix those?

root@raspberrypi:/home/ripeatlas# dpkg -i atlasswprobe-5020-1.deb
Selecting previously unselected package atlasswprobe.
(Reading database ... 49796 files and directories currently installed.)
Preparing to unpack atlasswprobe-5020-1.deb ...
Unpacking atlasswprobe (5020-1) ...
Setting up atlasswprobe (5020-1) ...
ripeatlas:x:1001:1001:,,,:/home/ripeatlas:/bin/bash
chown: invalid user: ‘atlas’
dpkg: error processing package atlasswprobe (--install):
 installed atlasswprobe package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 atlasswprobe
root@raspberrypi:/home/ripeatlas# adduser atlas

and another one:

root@raspberrypi:/home/ripeatlas# dpkg -i atlasswprobe-5020-1.deb
(Reading database ... 50223 files and directories currently installed.)
Preparing to unpack atlasswprobe-5020-1.deb ...
rmdir: failed to remove '/var/atlasdata': No such file or directory
rm: cannot remove '/var/atlas-probe/.ssh': No such file or directory
rm: cannot remove '/var/atlas-probe/crons': No such file or directory
rm: cannot remove '/var/atlas-probe/run': No such file or directory
rm: cannot remove '/var/atlas-probe/status': No such file or directory
dpkg: warning: old atlasswprobe package pre-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
rmdir: failed to remove '/var/atlasdata': No such file or directory
rm: cannot remove '/var/atlas-probe/.ssh': No such file or directory
rm: cannot remove '/var/atlas-probe/bin': No such file or directory
rm: cannot remove '/var/atlas-probe/crons': No such file or directory
rm: cannot remove '/var/atlas-probe/etc': No such file or directory
rm: cannot remove '/var/atlas-probe/run': No such file or directory
rm: cannot remove '/var/atlas-probe/state': No such file or directory
rm: cannot remove '/var/atlas-probe/status': No such file or directory
dpkg: error processing archive atlasswprobe-5020-1.deb (--install):
 new atlasswprobe package pre-removal script subprocess returned error exit status 1
ripeatlas:x:1001:1001:,,,:/home/ripeatlas:/bin/bash
atlas:x:1002:1002:,,,:/home/atlas:/bin/bash
Errors were encountered while processing:
 atlasswprobe-5020-1.deb
root@raspberrypi:/home/ripeatlas#

Thanks

**Comment by uiblogit** [comment]
Same here:
root@Rasp4B-srv1:/home/pi# dpkg -i atlasswprobe-5020-1.deb
(Reading database ... 118202 files and directories currently installed.)
Preparing to unpack atlasswprobe-5020-1.deb ...
rm: cannot remove '/var/atlas-probe/.ssh': No such file or directory
rm: cannot remove '/var/atlas-probe/bin': No such file or directory
rm: cannot remove '/var/atlas-probe/crons': No such file or directory
rm: cannot remove '/var/atlas-probe/run': No such file or directory
rm: cannot remove '/var/atlas-probe/state': No such file or directory
rm: cannot remove '/var/atlas-probe/status': No such file or directory
dpkg: warning: old atlasswprobe package pre-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
rmdir: failed to remove '/var/atlasdata': No such file or directory
rm: cannot remove '/var/atlas-probe/.ssh': No such file or directory
rm: cannot remove '/var/atlas-probe/bin': No such file or directory
rm: cannot remove '/var/atlas-probe/crons': No such file or directory
rm: cannot remove '/var/atlas-probe/etc': No such file or directory
rm: cannot remove '/var/atlas-probe/run': No such file or directory
rm: cannot remove '/var/atlas-probe/state': No such file or directory
rm: cannot remove '/var/atlas-probe/status': No such file or directory
dpkg: error processing archive atlasswprobe-5020-1.deb (--install):
 new atlasswprobe package pre-removal script subprocess returned error exit status 1
atlas:x:111:65534::/home/atlas:/usr/sbin/nologin
chown: cannot access '/var/atlas-probe': No such file or directory
dpkg: error while cleaning up:
 installed atlasswprobe package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 atlasswprobe-5020-1.deb
root@Rasp4B-srv1:/home/pi#

**Comment by uiblogit** [comment]
any solution?

**Comment by mbUSC** [comment]
Why was this closed?
I also ran into this issue
