### ISSUE TITLE
Systemd unit file does not restrict the service

### ISSUE THREAD

**Issue by ties** [RIPE-NCC/ripe-atlas-software-probe#44]
As a systems administrator I appreciate it when a systemd unit locks down the privileges its daemon have in order to reduce the attack surface.

It is not clear to me what the probe actually needs, but a separate `/tmp` and `/home` mount as well as not reading devices would likely work? A snippet from another daemon on my machine:
```
[Service]
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
DevicePolicy=closed
# DevicAllow=
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictRealtime=yes
RestrictNamespaces=yes
# Needed for python
MemoryDenyWriteExecute=no
```

**Comment by PhilipHomburg** [comment]
Feel free to come up with a patch
