### ISSUE TITLE
Software probes only connect to one controller?

### ISSUE THREAD

**Issue by virgiliomi** [RIPE-NCC/ripe-atlas-software-probe#45]
So, for the first time ever I got an email that my probe had been offline for a long period of time. So I started looking into why, and it appears that the controller that my probe normally connects to is offline.

So my next move is to see why it isn't connecting to other controllers... I know there are other controllers out there, as the built-in tests list at least 5 others. So I find a file in `/var/atlas-probe/status` called `known_hosts_controllers`, and all it has listed is the one controller (ctr-fsn01.atlas.ripe.net) and IPv4 and v6-only hostnames for the same controller. Sure enough, I go to the probes list on the website and every single software probe is offline, because we're all configured to use the same controller.

Is there a reason that our software probes aren't configured to use more than one controller? Is the controller that our probes use different because we're software probes? If the answers to both questions are no, then can the appropriate config file(s) be updated to allow us to connect to the other Atlas controllers? I know I'd prefer to use a different controller that is much closer to me network-wise (ctr-ewr01), since I'm in the US.

**Comment by PhilipHomburg** [comment]
This is not an ideal place to discuss how atlas works. It would be better to use the atlas mailing list (https://lists.ripe.net/mailman/listinfo/ripe-atlas). In any case, we have 2 controllers for software probes. Those controllers are kept separate from controllers for hardware probes. We placed both controllers at Hetzner and unfortunately Hetzner seem to have some issues recently (or at least more than I remember). Typically a controller handles about 500 probes, so it will take some time before we will get controllers in other places in the world.

Quite a bit of atlas backend logic depends on probes having just one controller at a time, so this is unlikely to change soon.

Sending probes to different controllers happens automatically, but it happens on a time scale of around 6 hours. It seems that the issue at Hetzner was less than 2 hours. However, with all controllers for software probes at Hetzner, a long failure at Hetzner would indeed impact all software probes.

**Comment by virgiliomi** [comment]
No worries then... I just thought this was something specific to software probes, so this might be the best place for it. Since it appears that you keep separate controllers for software probes vs hardware probes, I'll direct any further questions to the list, but that gives me enough info for now.
