### ISSUE TITLE
Please fix install documentation

### ISSUE THREAD

**Issue by ruben-herold** [RIPE-NCC/ripe-atlas-software-probe#5]
The install documentation just not work, the submodule source is not checkedout and can only checkout be a user with the credentials for your account cause the url is:

url = git@github.com:RIPE-NCC/ripe-atlas-probe-busybox.git

better would be https://github.com/RIPE-NCC/ripe-atlas-probe-busybox.git

**Comment by PhilipHomburg** [comment]
I fixed the URL of the submodule.

**Comment by ruben-herold** [comment]
Also you shout mention in the INSTALL.rst that the submodules are needed to build.
