### ISSUE TITLE
Not able to see system traffic on software probes

### ISSUE THREAD

**Issue by crazyuploader** [RIPE-NCC/ripe-atlas-software-probe#50]
I'm not able to see traffic history on my software probe, is there any settings I'm missing?

![Screenshot_20200912-103428_Chrome (1)](https://user-images.githubusercontent.com/49350241/92987817-a9199100-f4e3-11ea-8efd-369161fdce47.jpg)

**Comment by robert-kisteleki** [comment]
You need to opt in to traffic level reporting. Please take a look at https://github.com/RIPE-NCC/ripe-atlas-software-probe#runtime-configuration-options

**Comment by crazyuploader** [comment]
> You need to opt in to traffic level reporting. Please take a look at https://github.com/RIPE-NCC/ripe-atlas-software-probe#runtime-configuration-options

Worked great, thanks!
