### ISSUE TITLE
Building package on Ubuntu 18.04 installs but doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by schoen** [RIPE-NCC/ripe-atlas-software-probe#56]
Hi,

I built a deb package for the software probe during the deployathon a couple of weeks ago, and then installed the resulting deb package, on a VPS, but it failed to register successfully after that. Digging into this today, I found that the main loop shell script was running successfully, but it couldn't *do* anything because the Busybox applications had a dynamic linking error. The result is that all attempts by the software probe to take an action, including registration, would fail somewhat silently.

The Busybox binary that was built on Ubuntu 18.04 got dynamically linked against 

`	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fca48320000)`

but this library isn't present on Ubuntu 20.04. The deb package installs with no error (it doesn't declare an install-time dependency on a particular `libcrypto` version), yet each Busybox utility will then fail with

`someutility: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

I eventually got this working by building the software probe package directly on the same system where it was going to be run, but it would be nice not to have this constraint, or at least to get a more explicit warning about the library version conflict. (I also initially ran into #51 when building on 20.04.)

**Comment by PhilipHomburg** [comment]
I don't know enough about building debian packages to fix this. In theory there should a depenency on a particular version of openssl.

**Comment by michel-stam** [comment]
Hey guys,

Since this has been open since December 2020 I will close this issue for now.

We are currently working on refactoring the packaging for the software probe, which should make it easier to integrate various Linux flavours.

I agree with the above that it is most likely a dependency on a version of OpenSSL.
