### ISSUE TITLE
Won't build on centos 8 caused by libevent

### ISSUE THREAD

**Issue by ruben-herold** [RIPE-NCC/ripe-atlas-software-probe#6]
hi,

I fixed the spec file localy and checked out the submodule and try to build. I get the error:

`bufferevent_openssl.c:`` In function 'bio_bufferevent_new':
bufferevent_openssl.c:106:3: error: dereferencing pointer to incomplete type 'BIO' {aka 'struct bio_st'}
  b->init = 0;
   ^~
bufferevent_openssl.c: At top level:
bufferevent_openssl.c:228:1: error: variable 'methods_bufferevent' has initializer but incomplete type
 static BIO_METHOD methods_bufferevent = {
 ^~~~~~
bufferevent_openssl.c:79:27: warning: excess elements in struct initializer
 #define BIO_TYPE_LIBEVENT 57
                           ^~
bufferevent_openssl.c:229:2: note: in expansion of macro 'BIO_TYPE_LIBEVENT'
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^~~~~~~~~~~~~~~~~
bufferevent_openssl.c:79:27: note: (near initialization for 'methods_bufferevent')
 #define BIO_TYPE_LIBEVENT 57
                           ^~
bufferevent_openssl.c:229:2: note: in expansion of macro 'BIO_TYPE_LIBEVENT'
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^~~~~~~~~~~~~~~~~
bufferevent_openssl.c:229:21: warning: excess elements in struct initializer
  BIO_TYPE_LIBEVENT, "bufferevent",
                     ^~~~~~~~~~~~~
bufferevent_openssl.c:229:21: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:230:2: warning: excess elements in struct initializer
  bio_bufferevent_write,
  ^~~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:230:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:231:2: warning: excess elements in struct initializer
  bio_bufferevent_read,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:231:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:232:2: warning: excess elements in struct initializer
  bio_bufferevent_puts,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:232:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:233:2: warning: excess elements in struct initializer
  NULL /* bio_bufferevent_gets */,
  ^~~~
bufferevent_openssl.c:233:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:234:2: warning: excess elements in struct initializer
  bio_bufferevent_ctrl,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:234:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:235:2: warning: excess elements in struct initializer
  bio_bufferevent_new,
  ^~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:235:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:236:2: warning: excess elements in struct initializer
  bio_bufferevent_free,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:236:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:237:2: warning: excess elements in struct initializer
  NULL /* callback_ctrl */,
  ^~~~
bufferevent_openssl.c:237:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:228:19: error: storage size of 'methods_bufferevent' isn't known
 static BIO_METHOD methods_bufferevent = {
                   ^~~~~~~~~~~~~~~~~~~

Also the libevent is very very old.

**Comment by ja-pa** [comment]
I looks that with changes from https://github.com/libevent/libevent/commit/3e9e0a0d46e4508e8782ec3787c6d86bab63046d build successfully passes

**Comment by PhilipHomburg** [comment]
I noticed this as well when trying to get the software probe to run on debian 9 and 10.

Moving to a newer libevent solves the issue. However, there are some atlas specific patches to libevent. I will add those when I have time.

**Comment by PhilipHomburg** [comment]
I updated libevent to 2.1.11 and added support for CentOS 8
