### ISSUE TITLE
if_inet6 not enabled causes errors

### ISSUE THREAD

**Issue by alexdelprete** [RIPE-NCC/ripe-atlas-software-probe#62]
Hi,

I was having an issue with my probe on a Raspberry Pi 4B: no traffic data was sent.

I checked syslog and found out that when capturing traffica data from local interfaces, it was ok for LAN interface but then it queried interface `if_inet6` that didn't exist because ipv6 was disabled, so the script threw an error and no data was sent.

This error should be prevented by checking which interfaces are available and which one is used to connect.

Thanks,

Alessandro

**Comment by PhilipHomburg** [comment]
It looks like some old code is left behind in rxtxrpt. I'll take a look if it is safe to remove. Note that this is actually about the ripe-atlas-probe-busybox repo.

**Comment by alexdelprete** [comment]
Sorry for that, I read `ripe-atlas-software-probe` and thought it was for any software version of the probe.

Which one is the repo for software probe for RPi/debian?

**Comment by PhilipHomburg** [comment]
The repo consists of two parts. This one is the top level repo that contains the build scripts (for debian and centos) and the shell scripts for the probe. This repo refers to https://github.com/RIPE-NCC/ripe-atlas-probe-busybox for the actual measurement code and statistics.

**Comment by alexdelprete** [comment]
So where should I have opened the issue?

**Comment by PhilipHomburg** [comment]
The busybox repo would have been better.
