### ISSUE TITLE
Software probe not reporting traffic

### ISSUE THREAD

**Issue by aidvu** [RIPE-NCC/ripe-atlas-software-probe#64]
Hey there,

I ran a software probe before on my Turis Omnia router, on firmware 5020. It wasn't reporting any traffic then either, but at least the graph was showing the dates and no traffic.

I bought an OpenWRT (21.02.1) compatible router yesterday. Here's the probe: https://atlas.ripe.net/probes/1003553/. The probe is working well, but no traffic has been reported yet. Running firmware 5040. Since I switched to this new router the graph won't even go after 2022-01-25 12:30.

Looked at logs:
```
Wed Jan 26 13:57:28 2022 local6.err perd[2149]: USER root pid   0 cmd httppost -A 9015 --set-time 2 --delete-file --maxpostsize 9000000 --post-header /home/atlas/status/p_to_c_report_header --post-dir /home/atlas/data/out --post-footer /home/atlas/status/con_session_id.txt -O /home/atlas/data/new/main_sent.vol http://127.0.0.1:8080/?PROBE_ID=1003553&SESSION_ID={my_session_id} >> /home/atlas/data/new/main
Wed Jan 26 13:57:28 2022 local6.err perd[2149]: USER root pid   0 cmd condmv -A "RESULT 9901 ongoing" /home/atlas/data/new/main /home/atlas/data/out/main
Wed Jan 26 13:57:55 2022 local6.err perd[2149]: USER root pid   0 cmd condmv -A "RESULT 9901 ongoing" /home/atlas/data/new/main /home/atlas/data/out/main
Wed Jan 26 13:57:59 2022 local6.err perd[2149]: USER root pid   0 cmd httppost -A 9015 --set-time 2 --delete-file --maxpostsize 9000000 --post-header /home/atlas/status/p_to_c_report_header --post-dir /home/atlas/data/out --post-footer /home/atlas/status/con_session_id.txt -O /home/atlas/data/new/main_sent.vol http://127.0.0.1:8080/?PROBE_ID=1003553&SESSION_ID={my_session_id} >> /home/atlas/data/new/main
Wed Jan 26 13:58:06 2022 user.notice atlas-sw-probe: Probe ID is 1003553
Wed Jan 26 13:58:51 2022 local6.err perd[2149]: USER root pid   0 cmd httppost -A 9015 --set-time 2 --delete-file --maxpostsize 9000000 --post-header /home/atlas/status/p_to_c_report_header --post-dir /home/atlas/data/out --post-footer /home/atlas/status/con_session_id.txt -O /home/atlas/data/new/main_sent.vol http://127.0.0.1:8080/?PROBE_ID=1003553&SESSION_ID={my_session_id} >> /home/atlas/data/new/main
```

This is the only thing that sticks out. The `/home/atlas` folder didn't exist, so I created a symlink to the ones that do exist and have the files/folders referenced, in this case `/tmp/ripe_atlas_probe/`. Any tips would be appreciated. :)

**Comment by PhilipHomburg** [comment]
There should be no to create /home/atlas. Your problem is a backend problem. I'll try to have it fixed.

**Comment by aidvu** [comment]
> There should be no to create /home/atlas. 

I guess you meant to say `no need`. Removing the folders anyway, since it didn't fix anything. 

> Your problem is a backend problem. I'll try to have it fixed.

Highly appreciated.

**Comment by PhilipHomburg** [comment]
That's good question. Basically what we do is report statistics of all interfaces and the routing table. Then we assume that we need the statistics of interfaces that have a default route.

If it works correctly, any additional down stream interfaces will be ignored. Of course we can't tell the difference between traffic generated by the probe and other sources of traffic.

**Comment by aidvu** [comment]
> That's good question. Basically what we do is report statistics of all interfaces and the routing table. Then we assume that we need the statistics of interfaces that have a default route.

Guessed this much based on the debug logs. Thanks for confirming.
```
{ "name": "wan", "bytes_recv": 5962302, "pkt_recv": 52389, "errors_recv": 0, "dropped_recv": 0, "fifo_recv": 0, "framing_recv": 0, "compressed_recv": 0, "multicast_recv": 0, "bytes_sent": 17124710, "pkt_sent": 49966, "errors_sent": 0, "dropped_sent": 0, "fifo_sent": 0, "collisions_sent": 0, "carr_lost_sent": 0, "compressed_sent": 0 } ...
```

> If it works correctly, any additional down stream interfaces will be ignored. Of course we can't tell the difference between traffic generated by the probe and other sources of traffic.

Makes sense. I'll use this one as a dedicated software probe then.

Feel free to ping if you need any additional info from me.

**Comment by PhilipHomburg** [comment]
Your issue with the traffic statistics should be fixed.

**Comment by aidvu** [comment]
Seems to be working now.

I'm curious, what was the problem? Is there a way to avoid it? I can see the `measurement_id` switched from 1001 to 9002.

**Comment by PhilipHomburg** [comment]
We have limits on the size of measurement results. In your case, the size of the traffic statistics exceeded the limit. The fix was to increase the limit.

I don't know where the 1001 is coming from, that's a ping to k.root-servers.net. The traffic statistics is indeed measurement 9002.

**Comment by aidvu** [comment]
> Hmm, I guess I was looking at the defaults here: https://stat.ripe.net/m/widget/atlas-probe-traffic

I don't know where the 1001 is coming from, that's a ping to k.root-servers.net. The traffic statistics is indeed measurement 9002.

> We have limits on the size of measurement results. In your case, the size of the traffic statistics exceeded the limit. The fix was to increase the limit.

Ah, I see. Most likely because it was installed on a router which was an AP point. Would've been way over whatever the limits are for a probe.

Anyway, using this one as a dedicated probe. Thanks for the help. Closing issue.
