### ISSUE TITLE
Purpose of %post section in atlasswprobe.spec.in?

### ISSUE THREAD

**Issue by robert-scheck** [RIPE-NCC/ripe-atlas-software-probe#68]
As of writing, https://github.com/RIPE-NCC/ripe-atlas-software-probe/blob/master/build-config/centos/spec/atlasswprobe.spec.in has a quite large `%post` section, but why? Normally the creation of directories should haben in `%install` and the created directories with its permissions (if different from default) should be catched via `%files` section. Does the current way of different handling have a specific purpose?

**Comment by michel-stam** [comment]
Hi Robert,

Were currently looking at the spec files critically and will take your comment along. Thanks for mentioning!

Regards,

Michel
