### ISSUE TITLE
firmware 5070

### ISSUE THREAD

**Issue by Tuffiglig** [RIPE-NCC/ripe-atlas-software-probe#70]
Hey.
I saw here:
https://atlas.ripe.net/resources/announcements/
that firmware version 5070 is out.
But in this repo it is still version 5040.

Tuffi

**Comment by michel-stam** [comment]
Hi Tuffi,

Sorry about that, we were reorganising the repository to facilitate automatic building of releases. Because of that, we kept back from pushing our internal repository to the GitHub page. We'll be pushing it shortly.

Regards,

Michel

**Comment by fiergna** [comment]
Any updates on this case?

**Comment by Zeik0s** [comment]
If you don't want to wait i have created some releases for v5060 from the `devel` branch: [releases](https://github.com/Zeik0s/ripe-atlas-software-probe/releases/tag/v5060 )

**Comment by michel-stam** [comment]
Hi @fiergna,

We're testing the 5080 release right now. With the holidays it has taken a bit longer than we would have wanted, sorry about that.

We will release it for internal testing hopefully this week, then start looking at a production release next week or the week after (depending if the testing progresses according to plan).

Thanks for bearing with us.

Regards,

Michel

**Comment by michel-stam** [comment]
hi @fiergna ,

5080 is being released, I am working with a colleague to push the repo to GitHub sometime this week.

Regards

Michel

**Comment by alexdelprete** [comment]
> 5080 is being released, I am working with a colleague to push the repo to GitHub sometime this week.

Hi Michel, any updates on this?

**Comment by alexdelprete** [comment]
Hi Michel, no problem at all, and thank you very much for the update. :)

**Comment by michel-stam** [comment]
Hi Alex,

Software has just been pushed! 

Cheers,

Michel

**Comment by Tuffiglig** [comment]
Updated one of my software probes.
Seems to work :-)
https://atlas.ripe.net/probes/1000249/

The file [CHANGES.rst](https://github.com/RIPE-NCC/ripe-atlas-software-probe/blob/master/CHANGES.rst) is not updates.
Last entry is for Version 5040

**Comment by alexdelprete** [comment]
> Hi Alex,
> 
> Software has just been pushed!

Thanks a lof Michel. :)

**Comment by michel-stam** [comment]
CHANGES.rst was indeed not updated, made an issue out of it. We're looking to put the changelog in a single place, its in about 4 places at the moment.

Please find it here for now (this will change in the near future):
[https://atlas.ripe.net/resources/announcements/](https://atlas.ripe.net/resources/announcements/)
