### ISSUE TITLE
How to activate bandwith probes ?

### ISSUE THREAD

**Issue by vincegre** [RIPE-NCC/ripe-atlas-software-probe#73]
Hi

Reading the presentation on RIPE website it looks like some additional probes can be activated in the probe itself but I can't find any mention about how to do that on github repo :( How is it possible ?

Thanks

Vincèn

**Comment by michel-stam** [comment]
Hi Vincen

I'm not sure what you would like to know about activating probes in the probes. From the title I assume you mean bandwidth reporting. This can be activated by adding the line:
RXTXRPT=yes

to /var/atlas-probe/state/config.txt

then restart atlas (systemctl restart ATLAS).

Please let me know if this is what you mean. If not, can you point out the presentation to me?

Regards,

Michel
