### ISSUE TITLE
REST API for the connection status of the probe

### ISSUE THREAD

**Issue by alexdelprete** [RIPE-NCC/ripe-atlas-software-probe#75]
Hi,

on the webpage of the probe, there's a status tab which provides the conenction status of the probe.

![image](https://user-images.githubusercontent.com/7027842/201113560-9a735d1e-3f27-46d8-aeab-664308967fd5.png)

I'd like to know if there's a REST API for that status so that we can integrate the status of the probe in a management system. I took a look at REST API list but couldn't find me, I thought maybe it's not documented.

Hope you can help, thanks.

**Comment by michel-stam** [comment]
Hi @alexdelprete,

I will answer this for you, but this GIT relates to the software probe code, not to the user interface.

Is this what you're looking for?
https://atlas.ripe.net/api/v2/probes/60047/

Where 60047 is the probe id; it returns JSON formatted code which contains an object called "status". 

Regards,

Michel

**Comment by alexdelprete** [comment]
> Is this what you're looking for? https://atlas.ripe.net/api/v2/probes/60047/
> 
> Where 60047 is the probe id; it returns JSON formatted code which contains an object called "status".

Michel, thanks a lot for the info. I don't know why but I wasn't able to find the relevant docs, now I found it: https://atlas.ripe.net/docs/apis/rest-api-reference/#probes

BR,

Alessandro
