### ISSUE TITLE
Software probe stops measuring

### ISSUE THREAD

**Issue by rennyleal** [RIPE-NCC/ripe-atlas-software-probe#76]
Hi. Recently I've registered successfully a software probe but I'm having an issue with it. All of the sudden the probe, even though is up, it stops measuring, deletes some tags and stays so until I cicle stop/disable/enable/start the service. There is no apparently useful messages in the log file.

Also, I see an interesting difference compared with my old hardware probe. It uses a lot of bandwidth mostly inbound.

The software (5040) probe runs on a OpenWRT router since about a couple of weeks

Thanks in advance

**Comment by gcovain** [comment]
Hi, 
The bandwith thing might be a false positive : the traffic reported is not the one generated by measurements but the traffic for the host, so in the case of software probe if it is not running in some sort of container (like docker) then you get numbers about the total traffic flowing through your router.

**Comment by rennyleal** [comment]
Hi Michel

No problem, you can close it now

Regards


El 21 nov. 2022 9:34 a. m., michel-stam ***@***.***> escribió:

Hello Renny,

If you don't mind I will close the ticket here, you have a ticket open via ***@***.******@***.***>

Let me know.

Regards,

Michel
