### ISSUE TITLE
Fail to start atlas.service

### ISSUE THREAD

**Issue by masterAllen** [RIPE-NCC/ripe-atlas-software-probe#77]
OS: CentOS 7

the file `/usr/loca/atlas/bin/ATLAS` will give the following output:
![image](https://user-images.githubusercontent.com/26152844/206916654-bf9447df-4a9c-4862-bf9a-a257f2e0caf9.png)

My probe does not have IPv6 but I see the output shows the atlas tries to use ipv6 address.

**Comment by Ernst2020** [comment]
Yes. To find out whether your setup has IPv6 support it will try to connect to a controller using IPv6. If it fails to do so for some time, your probe will not be tagged to support IPv6.
Normal behavior, not an issue.

**Comment by phicoh** [comment]
For an Atlas probe it is vitally important to be able to reach a registration server, even if DNS resolution is broken. For this reason the probe tries the two names of the servers (reg03.atlas.ripe.net and reg04.atlas.ripe.net) as well as the IPv4 and IPv6 addresses of the servers.

At this point in the script it doesn't seem worthwhile finding out if the probe actually has IPv6 connectivity, and it may decrease robustness to try that route.

**Comment by phicoh** [comment]
Ah, your question was about the last line (that starts with RESULT). This is a special trick. The probe tries to perform a ping measurement but the host to ping is <something>.sos.atlas.ripe.net. The actual goal here is to capture the DNS request. Whether the ping succeeds or not is not important.

**Comment by masterAllen** [comment]
Thanks for reply! 
I have reinstalled the probe and succeeded to start service in this time :)
