### ISSUE TITLE
swprobe SSH public key missing

### ISSUE THREAD

**Issue by swapneelp** [RIPE-NCC/ripe-atlas-software-probe#8]
The directory /var/atlas-probe/etc is missing. 

`[root@ad43ce819c3b ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)`

`[root@ad43ce819c3b ~]# rpm -qa | grep atlas
ripe-atlas-repo-1-2.el7.noarch
atlasswprobe-5000-2.el7.x86_64`

`[root@ad43ce819c3b atlas-probe]# ls -al
total 40
drwxr-xr-x 7 atlas atlas 4096 Oct 23 09:29 .
drwxr-xr-x 1 root  root  4096 Oct 23 09:29 ..
-rw-r--r-- 1 atlas atlas   18 Oct 30  2018 .bash_logout
-rw-r--r-- 1 atlas atlas  193 Oct 30  2018 .bash_profile
-rw-r--r-- 1 atlas atlas  231 Oct 30  2018 .bashrc
drwxr-xr-x 2 atlas atlas 4096 Oct 23 09:29 bin
drwxr-xr-x 5 atlas atlas 4096 Oct 23 09:29 crons
drwxrwxr-x 5 atlas atlas 4096 Oct 23 09:29 data
drwxr-xr-x 2 atlas atlas 4096 Oct 23 09:29 run
drwxr-xr-x 2 atlas atlas 4096 Oct 23 09:29 state`

`[root@ad43ce819c3b atlas-probe]# rpm -qa | grep openssh
openssh-7.4p1-21.el7.x86_64`

Let me know if any additional information/debugging is required to look into this issue.

**Comment by PhilipHomburg** [comment]
Does 'systemctl | grep atlas' give '  atlas.service                                                                            loaded active running   Atlas Probe'?

To debug, edit '/usr/local/atlas/bin/ATLAS' and uncomment the two lines '#exec >/tmp/ATLAS.out 2>/tmp/ATLAS.err' and '#set -x' and restart atlas.

**Comment by swapneelp** [comment]
Hey @PhilipHomburg! Thanks for looking into this. I forgot to mention that I was testing this inside a Docker container. 

atlas.service wasn't loaded. By starting the container in privileged mode, the service loads and the /var/atlas-probe/etc directory exists along with private & public keys. 

Submitted an application for the probe with the details.

**Comment by swapneelp** [comment]
@PhilipHomburg Would you know by any chance, how much time it takes for the software probe to start showing up on the probe page ? I got the confirmation email that the software probe has been created. Probe ID 1000008

**Comment by PhilipHomburg** [comment]
It takes some time for the ssh public key to propagate in our system. However, by the time you get the email it is usually in place.

A good place to look is /var/atlas-probe/status/ssh_err.txt 
That file often has a good hint why the probe does not connect.

**Comment by swapneelp** [comment]
@PhilipHomburg Thanks for pointing me in the right direction !  Since the docker image is bare, it lacked openssh-clients package which is required. 

I now see the probe page[https://atlas.ripe.net/probes/1000008/](url)

Data is not showing yet, in the ssh_err.txt, 

`[root@13ca77140d49 status]# cat ssh_err.txt
RSA host key for IP address '178.63.8.31' not in list of known hosts.
bind: Cannot assign requested address`

I am guessing, the swprobe configures a tunnel via ssh port forwarding and maybe since this is inside docker, it's not able to bind to a predefined port ?

**Comment by PhilipHomburg** [comment]
I'll add openssh-clients to the dependencies of the RPM.

Note that the atlas measurement code needs quite a few ports to be open, as well as raw socket capabilities.

**Comment by swapneelp** [comment]
@PhilipHomburg Thanks !

The CentOS 7 image is without a firewall and is running in privileged mode which should give it full access to running services and binding ports. 

I think the only possibility which remains is, the software-probe is trying to bind to a port which may already be taken on the host. Do you have a list of ports which I can verify against ?

**Comment by Knight1** [comment]
You have some more to do.

Are you in the Mailinglist? I just sent a mail with code and instructions. 

@PhilipHomburg at this time ```openssh-clients iproute sysvinit-tools net-tools``` are needed

**Comment by PhilipHomburg** [comment]
I added openssh-clients iproute sysvinit-tools net-tools and requirements. sysvinit-tools doesn't exist on CentOS 8.
