### ISSUE TITLE
RIPE-NCC

### ISSUE THREAD

**Issue by SchiffGold** [RIPE-NCC/ripe-atlas-software-probe#86]
Enter a search term
By submitting this form you explicitly express your agreement with the RIPE Database Terms and Conditions 

RIPE Database certificate
Earn the RIPE Database Associate certification

Do you use the RIPE Database regularly as a researching and data registration tool? You can earn a verifiable digital badge from the RIPE NCC that certifies your skills and expertise in using RIPE Database.
Find out more about how you can earn the RIPE Database Associate badge and get certified!
Search results

This is the RIPE Database search service. The objects are in RPSL format. The RIPE Database is subject to Terms and Conditions .

 Highlight RIPE NCC managed values
inetnum:         49.14.0.0 - 49.235.255.255
netname:         NON-RIPE-NCC-MANAGED-ADDRESS-BLOCK
descr:           IPv4 address block not managed by the RIPE NCC
remarks:         ------------------------------------------------------
remarks:         
remarks:         For registration information,
remarks:         you can consult the following sources:
remarks:         
remarks:         IANA
remarks:         http://www.iana.org/assignments/ipv4-address-space
remarks:         http://www.iana.org/assignments/iana-ipv4-special-registry
remarks:         http://www.iana.org/assignments/ipv4-recovered-address-space
remarks:         
remarks:         AFRINIC (Africa)
remarks:         http://www.afrinic.net/ whois.afrinic.net
remarks:         
remarks:         APNIC (Asia Pacific)
remarks:         http://www.apnic.net/ whois.apnic.net
remarks:         
remarks:         ARIN (Northern America)
remarks:         http://www.arin.net/ whois.arin.net
remarks:         
remarks:         LACNIC (Latin America and the Carribean)
remarks:         http://www.lacnic.net/ whois.lacnic.net
remarks:         
remarks:         ------------------------------------------------------
country:         EU # Country is really world wide
admin-c:         IANA1-RIPE
tech-c:          IANA1-RIPE
status:          ALLOCATED UNSPECIFIED
mnt-by:          RIPE-NCC-HM-MNT
created:         2020-11-02T15:29:05Z
last-modified:   2020-11-02T15:29:05Z
source:          RIPE
RIPE Database Software Version 1.106.1. [AI](https://apps.db.ripe.net/db-web-ui/query?searchtext=49.183.68.243)

**Comment by michel-stam** [comment]
Hi @SchiffGold I'm not sure what your question is?

Also, questions regarding the RIPE database are not within the scope of RIPE Atlas, another project. Can you redirect your question there?

I will close the ticket here.

Regards,

Michel
