### ISSUE TITLE
RIPE Atlas software probe on OpenWrt?

### ISSUE THREAD

**Issue by olekstomek** [RIPE-NCC/ripe-atlas-software-probe#89]
In [documentation ](https://atlas.ripe.net/docs/howtos/software-probes.html#platform-specific-installation-instructions) there is no information about [OpenWrt](https://github.com/openwrt). Is it possible to run measurements on OpenWrt software? More details?
I asked about running RIPE Atlas SW probe on the [forum OpenWrt](https://forum.openwrt.org/t/ripe-atlas-probe-in-openwrt/168721).

**Comment by lukastribus** [comment]
See:

https://parkercs.tech/running-a-ripe-atlas-probe-on-openwrt/

**Comment by olekstomek** [comment]
A very valuable guide! Maybe add this to the documentation ->https://github.com/openwrt/packages/blob/openwrt-22.03/net/atlas-sw-probe/files/atlas.readme ?

Packages:
- https://openwrt.org/packages/pkgdata/atlas-sw-probe-rpc
- https://openwrt.org/packages/pkgdata/atlas-sw-probe
- https://openwrt.org/packages/pkgdata/atlas-probe
