### ISSUE TITLE
IPv6 only is not registering

### ISSUE THREAD

**Issue by Knight1** [RIPE-NCC/ripe-atlas-software-probe#9]
```
Oct 25 06:19:34 bgp ATLAS[1355]: start reg
Oct 25 06:19:34 bgp ATLAS[1355]: ATLAS registeration starting
Oct 25 06:19:34 bgp ATLAS[1355]: REASON_FOR_REGISTRATION NEW NO previous state files
Oct 25 06:19:34 bgp ATLAS[1355]: REGHOSTS reg03.atlas.ripe.net 193.0.19.246 2001:67c:2e8:11::c100:13f6 reg04.atlas.ripe.net 193.0.19.247 2001:67c:2e8:11::c100:13f7
Oct 25 06:19:34 bgp ATLAS[1355]: ssh -i /var/atlas-probe/etc/probe_key -p 443 atlas@193.0.19.246 INIT
Oct 25 06:19:34 bgp ATLAS[1355]: tee: standard output: Broken pipe
Oct 25 06:19:34 bgp ATLAS[1355]: tee: write error
Oct 25 06:19:34 bgp ATLAS[1355]: 255  REGINIT exit with error
Oct 25 06:19:34 bgp ATLAS[1355]: RESULT { "id": "9001", "time": 1571984374, "macaddr": "56000261f5a3", "uptime": 63, "buddyinfo": [ 3, 4, 2, 2, 3, 1, 0, 2, 2, 1, 1 ], "freemem": 9676 }
```

I had to manually edit reg_servers.sh so that it only includes one IPv6 Entry.
The special thing is that the system has a public IPv4 address. But the Atlas software should retry it with other reg systems imho. 

We should implement a for loop here https://github.com/RIPE-NCC/ripe-atlas-software-probe/blob/439ea1bbadea5a48bbf1a2f43e198106632c7ced/bin/reginit.sh#L152 or a connectivity check around here https://github.com/RIPE-NCC/ripe-atlas-software-probe/blob/439ea1bbadea5a48bbf1a2f43e198106632c7ced/bin/reginit.sh#L138

**Comment by Knight1** [comment]
Any intention to speed that up?
Otherwise any PR would not make any sense :)

**Comment by PhilipHomburg** [comment]
No. Probes are meant to be running 24x7. The few minutes it takes to connect after a reboot are lost in the noise.
